spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-presentation?characterEncoding=utf-8
    username: root
    password: asdf
  data.repositories.enabled: true
  jpa:
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
          ddl-auto: update
  #        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
flyway.baseline-on-migrate: true